---
title: "5023Y"
---

<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

All lecture materials will be available here.

- 01: Introductions and course outline
    - [Slides](slides/Introduction.html)

    - [Practical work](https://ueabio.github.io/data-sci-v1/introduction-to-r-and-rstudio.html)

- 02: Using R
    - [Slides](slides/Intro_02.html)
    
    - [Practical work](https://ueabio.github.io/data-sci-v1/basic-programming.html)

- 03: Working with data
    - [Slides](slides/Data_wrangling_03.html)

    - [Practical work 1](https://ueabio.github.io/data-sci-v1/loading-data.html)
    - [Practical work 2](https://ueabio.github.io/data-sci-v1/data-wrangling-part-one.html)
    - [Practical work 3](https://ueabio.github.io/data-sci-v1/data-wrangling-part-two.html)
    
- 04: Data Visualisation
    - [Slides](slides/ggplot.html)
    
- 05: Reproducible Reports
    - [Slides](slides/Reproducible_reports_06.html)
    
- 06: Github
    - [Slides](slides/Github.html)
    
- 06: Functional programming
    - [Slides](slides/Functional-programming.html)

- 07: Exploratory Analysis
    - [Slides](slides/EDA.html)
    
- 08: Bad Data viz
    - [Slides](slides/Bad-plots.html)
    
- 09: Descriptive statistics
    - [Slides: Central tendency and spread](slides/Descriptive_statistics_05.html)

    - [Slides: Association](slides/Association_05a.html)

    - [Practical work](https://ueabio.github.io/data-sci-v1/data-insights-part-one.html)


- 10: Great Data Viz
    - [Slides: Great data visualisation](slides/Great_data_viz.html)

- 11: Confidence intervals
    - [Slides](slides/Confidence_intervals.html)

## Term 2

- 12: Introduction to Statistics
    - [Slides](slides/intro_stats.html)
    
- 13: Intro to linear models
    - [Slides](slides/intro-linear-model.html)

- 14: Hypothesis testing
    - [Slides: P-values](slides/Probability.html)
    - [Slides: Type 1 and Type 2 errors](slides/Error_rates.html)

- 15: T-tests
    - [Slides](slides/t-tests.html)
  
 
    
- 16: ANOVA
    - [Slides](slides/ANOVA.html)
  
- 17: Multivariate models
    - [Slides: Complex models](slides/Complex_models.html)
    - [Slides: Checking and refining models](slides/Refining models.html)
     
      
- 18: Generalised linear models

  - [Slides: Introduction to Generalised Linear Models](slides/Generalized-Linear-Models.html)

  - [Slides: Binomial and Poisson distributions](slides/Generalized-Linear-Models-Part-2.html)



    
